### ISSUE TITLE
Add option to select/deselect all on the infection graph per region

### ISSUE THREAD

**Issue by DiegoCardoso** [lovelldies/finland-corona-map#8]
Right now is a bit hard if you want to see the data from one or a few regions.

**Comment by DiegoCardoso** [comment]
Example: https://www.amcharts.com/docs/v4/tutorials/toggling-multiple-series-with-a-single-legend-item/#Separate_toggle_button

**Comment by lovelldies** [comment]
Sorry for the late response. For some reason, I did not receive the email alerts.

Thanks for the feedback. I shall look into this later today and will update you once it is done.

**Comment by DiegoCardoso** [comment]
It looks great! Thanks!
